# Generated by Django 5.1.7 on 2025-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('فرص عمل', 'فرص عمل'), ('أخبار الوفيات', 'أخبار الوفيات'), ('أخبار رياضية', 'أخبار رياضية'), ('أخبار الجالية', 'أخبار الجالية')], max_length=20, verbose_name='الفئة')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='صورة الخبر')),
            ],
        ),
    ]
