# Generated by Django 5.1.7 on 2025-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('فرص عمل', 'فرص عمل'), ('أخبار الوفيات', 'أخبار الوفيات'), ('أخبار رياضية', 'أخبار رياضية'), ('أخبار الجالية', 'أخبار الجالية')], max_length=50, verbose_name='القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
