# Generated by Django 5.1.7 on 2025-03-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_delete_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('فرص عمل', 'فرص عمل'), ('أخبار الوفيات', 'أخبار الوفيات'), ('أخبار رياضية', 'أخبار رياضية'), ('أخبار الجالية', 'أخبار الجالية')], max_length=50, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
