# Generated by Django 5.1.7 on 2025-03-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان النشاط')),
                ('content', models.TextField(verbose_name='محتوى النشاط')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='صورة النشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
            },
        ),
    ]
