# Generated by Django 5.1.7 on 2025-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('file', models.FileField(upload_to='regulations/', verbose_name='الملف (PDF / Word)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
