# Generated by Django 5.1.7 on 2025-03-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='file',
        ),
        migrations.AlterField(
            model_name='regulation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='RegulationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='regulations/')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regulations.regulation')),
            ],
        ),
    ]
