# Generated by Django 5.1.7 on 2025-03-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_remove_regulation_file_alter_regulation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulations/'),
        ),
        migrations.DeleteModel(
            name='RegulationFile',
        ),
    ]
