# Generated by Django 5.1.7 on 2025-03-25 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_regulation_file_delete_regulationfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='file',
        ),
        migrations.CreateModel(
            name='RegulationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='regulations/files/')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regulations.regulation')),
            ],
        ),
    ]
