# Generated by Django 5.1.7 on 2025-03-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=20)),
                ('family_members', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='votingsession',
            name='category',
            field=models.CharField(choices=[('منصب إداري', 'منصب إداري'), ('قرار', 'قرار'), ('استبيان', 'استبيان')], default='قرار', max_length=20),
        ),
    ]
