# Generated by Django 5.1.7 on 2025-03-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_member_votingsession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingsession',
            name='category',
            field=models.CharField(max_length=50, verbose_name='نوع التصويت (اكتب يدويًا)'),
        ),
    ]
