# Generated by Django 5.1.7 on 2025-03-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_votingsession_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('relationship', models.CharField(max_length=50, verbose_name='صلة القرابة')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members_data', to='vote.member')),
            ],
        ),
    ]
