# Generated by Django 5.1.7 on 2025-03-30 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_member_can_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingsession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='votingsession',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت بداية التصويت'),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='وقت انتهاء التصويت'),
        ),
    ]
