# Generated by Django 5.1.7 on 2025-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_votingsession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='حالة تسجيل الدخول'),
        ),
    ]
