# Generated by Django 5.1.7 on 2025-05-14 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_member_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'marital_status': 'متزوج'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouses', to='vote.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('طالب', 'طالب')], max_length=20),
        ),
    ]
