# Generated by Django 5.1.7 on 2025-05-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_member_spouse_alter_member_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spouse',
        ),
        migrations.AddField(
            model_name='member',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='institution_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة؟'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='تم الرفض؟'),
        ),
        migrations.AddField(
            model_name='member',
            name='transit_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='can_vote',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='نعم', max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
