# Generated by Django 5.1.7 on 2025-05-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_remove_member_spouse_member_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('VOID CHEQUE', 'VOID CHEQUE'), ('E-TRANSFER', 'E-TRANSFER'), ('CASH', 'CASH')], max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_period',
            field=models.CharField(blank=True, choices=[('شهري', 'شهري'), ('سنوي', 'سنوي')], max_length=10),
        ),
    ]
